name: 'A Custom Github Action for Shell Check'
description: 'That only used for learning'
inputs:
  dir:
    description: 'which dir need to scan'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
